version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: mapbox-gl
    versions:
    - 2.0.1
    - 2.1.0
    - 2.1.1
